/* eslint-disable no-unused-vars */
var restaurants = [
  { id: 0, name: 'Le Diplomate Cafe', type: 'Quick Bite', price: '$', distance: 5, address: '4237 Campus Drive Ste B 161', addressCity: 'Irvine, CA 92612', telephone: '(949) 854-5161', recommended: true, image: 'images/le-dip.jpg', description: 'Le Diplomate Cafe is the best place for lunch near the UCI marketplace. This small French/Vietnamese cafe makes amazing sandwiches. Try the garlic chicken sandwich!', menu: 'Chicken Broccoli Mushroom, Chicken Garlic, Chicken Dijon, Eggplant Sandwich' },
  { id: 1, name: 'Mick\'s Karma Bar', type: 'Quick Bite', price: '$', distance: 4, address: '2010 Main Street Ste 165', addressCity: 'Irvine, CA 92614', telephone: '(949) 851-6316', recommended: false, image: 'images/micks-burger.jpg', description: 'All the burgers are made with a signature steak haché patty that owes everything to the quality and the freshness of the meat. Each patty is made to order and is all natural without hormones or antibiotics.', menu: 'The Karma Burger, The Baja, The Karma Swiss Onion Style, Strawberry Basil Lemonade' },
  { id: 2, name: 'HiroNori Craft Ramen', type: 'Asian', price: '$$', distance: 10, address: '2222 Michelson Drive Ste 234', addressCity: 'Irvine, CA 92612', telephone: '(949) 536-5800', recommended: false, image: 'images/hironori.jpg', description: 'Hiro Nori is a craft ramen establishment. The owners aim to present a ramen restaurant that appeals to the diverse demographics of Southern California by offering the most delicious and most affordable ramen in a warm, modern Japanese atmosphere.', menu: 'Tonkotsu Chashu Ramen, Shoyu Chashu Ramen, Poke Rice Bowl' },
  { id: 3, name: 'Dada Shabu Shabu Buffet', type: 'Asian', price: '$$', distance: 6, address: '4960 Irvine Blvd', addressCity: 'Irvine, CA 92620', telephone: '(714) 544-9300', recommended: true, image: 'images/dada-cropped.jpg', description: 'All you can eat Korean shabu shabu with buffet sides such as chicken wings, tempura, topokki, and more! Soda, coffee, tea and shaved ice are ALL included!', menu: 'Chuck Top Blade, Wagyu Beef Belly, Basa Fish Fillet, Chicken Wings, Snow Ice' },
  { id: 4, name: 'Wow Bento', type: 'Asian', price: '$', distance: 3, address: '10 McLaren', addressCity: 'Irvine, CA 92618', telephone: '(949) 699-0808', recommended: false, image: 'images/wow-bento.jpg', description: 'A poke bowl restaurant that allows you to order your meal in an assembly-line fashion. Wow Bento even offers a poki-ritto option!', menu: 'Poke Bowl, Poke Wrap, Salmon Sashimi, Albacore Sashimi, Shrimp, Tuna Sashimi, Octopus' },
  { id: 5, name: 'Burntzilla', type: 'American', price: '$', distance: 1, address: '14413 Culver Drive', addressCity: 'Irvine, CA 92606', telephone: '(949) 392-5995', recommended: true, image: 'images/burntzilla-cropped.jpg', description: 'BurntZilla is a union between two of the top food trucks in Orange County. At BurntZilla, you will find a bold variety of classic comfort food options in mini form that will make a big impact on your taste buds!', menu: 'Fried Chicken Burger, Fried Cheese Burger, Sloppy Joe Burger, Dogzilla, Loaded Tater Tots' },
  { id: 6, name: 'The Kroft', type: 'American', price: '$$', distance: 7, address: '2493 Park Ave', addressCity: 'Tustin, CA 92782', telephone: '(657) 900-8451', recommended: false, image: 'images/the-kroft.jpg', description: 'The Kroft opened its doors in 2014 with locations all over Southern California. The restaurant encompasses a whirlwind of fast casual gastropub fare paired with local production craft beers. Their speciality, poutine fries, is piled with fresh cheese curds, homemade gravies, and signature toppings to reinterpret the Canadian classic.', menu: 'Classic Poutine, Braised Short Rib Poutine, Prime Ribeye Dip Sandwich, Hot Cheetos Cheesesteak Bao Buns, Garlic Fries' },
  { id: 7, name: 'Butterleaf', type: 'Vegetarian', price: '$$', distance: 2, address: '2222 Michelson Drive', addressCity: 'Irvine, CA 92612', telephone: '(949) 932-0420', recommended: false, image: 'images/butterleaf.jpg', description: 'Vegetarian food for non-vegetarians! Butterleaf aims to please the masses with their plant-based cuisine. Hearty food packed with nutrition, not guilt. Who said eating healthy can\'t be indulgent and filling?', menu: 'Signature Butterleaf Burger, Scratch-Made Veggie Burger, Avocado Bombs, Build Your Own Bowl' },
  { id: 8, name: 'CUCINA enoteca Irvine', type: 'Italian', price: '$$', distance: 3, address: '532 Spectrum Center Drive', addressCity: 'Irvine, CA 92618', telephone: '949-861-2222', recommended: false, image: 'images/cucina-enoteca.jpg', description: 'CUCINA enoteca, a California-inspired Italian kitchen and wine shop, evokes a modern kitchen coupled with the history and comfort of an old rustic country farmhouse. The menu features Italian classics made with the freshest local produce, and organic and sustainable ingredients.', menu: 'Burrata Prosciutto Caprese, Giant Meatball, Pizza, Short Rib Pappardelle' },
  { id: 9, name: 'Tender Greens', type: 'Salad', price: '$$', distance: 7, address: '530 Spectrum Center Drive', addressCity: 'Irvine, CA 92618', telephone: '(949) 679-9135', recommended: false, image: 'images/tender-greens.jpg', description: 'Tender Greens is a fine casual restaurant that combines our fine dining point of view and hospitality with a casual, quick dining atmosphere. Our restaurants serve fresh, healthy, chef-inspired, farmer\'s market sensible dishes at an affordable price in a relaxed environment.', menu: 'Backyard Marinated Steak, Herb Brushed Albacore, Kale, Butter Lettuce, Roasted Tomato Soup' },
  { id: 10, name: 'Cream Pan', type: 'Desserts', price: '$', distance: 1, address: '602 El Camino Real', addressCity: 'Tustin, CA 92780', telephone: '(714) 665-8239', recommended: false, image: 'images/cream-pan.jpg', description: 'A Japanese bakery that is known for their shockingly delicious strawberry custard croissants, baguettes, and epi bread. Cream Pan\'s goodies are reminiscent of crowded boulangeries in Paris and scream for just a little sweet butter and maybe a touch of jam before being dunked into coffee, Japanese-French style.', menu: 'Strawberry Croissant, Strawberry Banana Croissant, Bageutte, Turkey Avocado Sandwich' }
]
