/* eslint-disable no-unused-vars */
var restaurants = [
  { id: 0, name: 'Le Diplomate Cafe', type: 'Quick Bite', price: '$', distance: 5, address: '4237 Campus Drive Ste B 161', addressCity: 'Irvine, CA 92612', telephone: '(949) 854-5161', recommended: true, image: 'images/le-dip.jpg', description: 'Le Diplomate Cafe is the best place for lunch near the UCI marketplace. This small French/Vietnamese cafe makes amazing sandwiches. Try the garlic chicken sandwich!' },
  { id: 1, name: 'Mick\'s Karma Bar', type: 'Quick Bite', price: '$', distance: 4, address: '2010 Main Street Ste 165', addressCity: 'Irvine, CA 92614', telephone: '(949) 851-6316', recommended: false, image: 'images/micks-burger.jpg' },
  { id: 2, name: 'HiroNori Craft Ramen', type: 'Asian', price: '$$', distance: 10, address: '2222 Michelson Drive Ste 234', addressCity: 'Irvine, CA 92612', telephone: '(949) 536-5800', recommended: false, image: 'images/hironori.jpg' },
  { id: 3, name: 'Dada Shabu Shabu Buffet', type: 'Asian', price: '$$', distance: 6, address: '4960 Irvine Blvd', addressCity: 'Irvine, CA 92620', telephone: '(714) 544-9300', recommended: true, image: 'images/dada-cropped.jpg', description: 'All you can eat Korean shabu shabu with buffet sides such as chicken wings, tempura, topokki, and more! Soda, coffee, tea and shaved ice are ALL included!' },
  { id: 4, name: 'Wow Bento', type: 'Asian', price: '$', distance: 3, address: '10 McLaren', addressCity: 'Irvine, CA 92618', telephone: '(949) 699-0808', recommended: false, image: 'images/wow-bento.jpg' },
  { id: 5, name: 'Burntzilla', type: 'American', price: '$', distance: 1, address: '14413 Culver Drive', addressCity: 'Irvine, CA 92606', telephone: '(949) 392-5995', recommended: true, image: 'images/burntzilla-cropped.jpg', description: 'BurntZilla is a union between two of the top food trucks in Orange County. At BurntZilla, you will find a bold variety of classic comfort food options in mini form that will make a big impact on your taste buds!' },
  { id: 6, name: 'The Kroft', type: 'American', price: '$$', distance: 7, address: '2493 Park Ave', addressCity: 'Tustin, CA 92782', telephone: '(657) 900-8451', recommended: false, image: 'images/the-kroft.jpg' },
  { id: 7, name: 'Butterleaf', type: 'Vegetarian', price: '$$', distance: 2, address: '2222 Michelson Drive', addressCity: 'Irvine, CA 92612', telephone: '(949) 932-0420', recommended: false, image: 'images/butterleaf.jpg' },
  { id: 8, name: 'CUCINA enoteca Irvine', type: 'Italian', price: '$$', distance: 3, address: '532 Spectrum Center Drive', addressCity: 'Irvine, CA 92618', telephone: '949-861-2222', recommended: false, image: 'images/cucina-enoteca.jpg' },
  { id: 9, name: 'Tender Greens', type: 'Salad', price: '$$', distance: 7, address: '530 Spectrum Center Drive', addressCity: 'Irvine, CA 92618', telephone: '(949) 679-9135', recommended: false, image: 'images/tender-greens.jpg' },
  { id: 10, name: 'Cream Pan', type: 'Desserts', price: '$', distance: 1, address: '602 El Camino Real', addressCity: 'Tustin, CA 92780', telephone: '(714) 665-8239', recommended: false, image: 'images/cream-pan.jpg' }
]
